SELECT
    JE_CATEGORY_NAME,
    JE_CATEGORY_KEY,
    USER_JE_CATEGORY_NAME,
    DESCRIPTION,
    CONSOLIDATION_FLAG,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY
FROM gl_je_categories
ORDER BY JE_CATEGORY_NAME