SELECT
    gjc.JE_CATEGORY_NAME,
    gjc.JE_CATEGORY_KEY,
    gjc.USER_JE_CATEGORY_NAME,
    gjc.DESCRIPTION,
    gjc.CONSOLIDATION_FLAG,
    gjc.CREATION_DATE,
    gjc.CREATED_BY,
    gjc.LAST_UPDATE_DATE,
    gjc.LAST_UPDATED_BY,
    gjc.OBJECT_VERSION_NUMBER
FROM gl_je_categories gjc
ORDER BY JE_CATEGORY_NAME